### ISSUE TITLE
Adjust attach syntax for Backdrop.

### ISSUE THREAD

**Issue by Wylbur** [backdrop-contrib/gin#159]
I have the RC3 version of the module installed.  
Editing a node with a body field.  
Using CKEditor5, and trying to insert a image via the media module.  

The media overlay never appears, I just get a small overlay with the word "Loading".

Here's the error message from the console

description_toggle.js?v=1.32.1:4 
```
Uncaught TypeError: context.querySelectorAll is not a function
    at Object.attach (description_toggle.js?v=1.32.1:4:15)
    at Object.<anonymous> (backdrop.js?v=1.32.1:73:12)
    at ce.each (jquery.js?v=3.7.1:2:3179)
    at Backdrop.attachBehaviors (backdrop.js?v=1.32.1:71:5)
    at Object.insert (ajax.js?v=1.32.1:675:16)
    at Backdrop.ajax.commands.openDialog (<anonymous>:91:17)
    at Backdrop.ajax.success (ajax.js?v=1.32.1:513:42)
    at Object.success (ajax.js?v=1.32.1:241:19)
    at c (jquery.js?v=3.7.1:2:25304)
    at Object.fireWith [as resolveWith]
```
Switching to the Seven admin theme resolves the issue for me.

**Comment by laryn** [comment]
@Wylbur Can you try turning off the "Hide descriptions" option in Gin and see if it changes things? The error looks like it may be related to that setting.

**Comment by Wylbur** [comment]
@laryn YES, disabling the "Enable form description toggle" does resolve the issue with using media in the CKEditor window!  

This has no effect on  the dark/light/auto mode.

**Comment by laryn** [comment]
@Wylbur I pushed a commit but would still love if you could verify it works for you. It looks like I let slip through a syntax change during a pull from the Drupal upstream:
- https://github.com/backdrop-contrib/gin/commit/b851e2e720222aabbe8147a5e5197652cc6f4158

**Comment by laryn** [comment]
This is in the [latest release](https://github.com/backdrop-contrib/gin/releases/tag/1.x-5.0.0) -- if verified by @Wylbur we can close this issue.

**Comment by avpaderno** [comment]
Using the lastest release, I cannot reproduce this issue.

<img width="945" height="677" alt="Image" src="https://github.com/user-attachments/assets/40b46bc9-be65-487d-ad63-0795a1f71bda" />

I got that dialog box clicking on the highlighted icon in the following screenshot, which was one of the icons shown by CkEdit 5 for a _Body_ field. (In my case, it was for a _Post_ node.)

<img width="339" height="62" alt="Image" src="https://github.com/user-attachments/assets/29ec183a-3612-4c9d-af77-534183cfa221" />

**Comment by laryn** [comment]
Thanks @avpaderno! If you continue to see an issue with the latest release, please reopen, @Wylbur.

**Comment by Wylbur** [comment]
WOW, this works, but it took some work on my part to get it working.  I cleared caches, and switched themes, but it was still not working.  

What DID work was to set admin theme as Seven, disable GIN, then enable, then set as admin theme.  

Great work @laryn and @avpaderno

**Comment by herbdool** [comment]
@laryn even with commit https://github.com/backdrop-contrib/gin/commit/1047d690459b481b6d307492e35bec9ee08c53cd enabling "Enable form description toggle" breaks the JS.

**Comment by laryn** [comment]
@herbdool Where are you seeing it break? That commit fixed it on the page I was seeing it.

**Comment by herbdool** [comment]
@laryn on the Gin settings page, node forms, etc.

**Comment by laryn** [comment]
@herbdool Oof. Clearly didn't look that one over closely enough. Are you able to test this?
https://github.com/backdrop-contrib/gin/pull/161
